services:
  trustdeck-frontend:
    container_name: trustdeck-frontend
    image: trustdeck-frontend:latest
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      args:
        http_proxy: ${http_proxy:-}
        https_proxy: ${https_proxy:-}
        no_proxy: ${no_proxy:-}
        HTTP_PROXY: ${HTTP_PROXY:-}
        HTTPS_PROXY: ${HTTPS_PROXY:-}
        NO_PROXY: ${NO_PROXY:-}
    env_file:
      - ${FRONTEND_ENV_FILE:-./trustdeck-frontend.env}
    ports:
      - "${FRONTEND_BIND:-127.0.0.1:8082}:8080"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
