import { useEffect, useRef, useState } from 'react'
import useProjectStore from '../../../core/stores/ProjectStore'
import Panel from '@component/common/Panel'
import { parseAttributes } from './FormParser'
import { setValue } from '../util/value'
import { useTranslation } from 'react-i18next'
import { useNavigate } from 'react-router-dom'
import { Stepper } from 'primereact/stepper'
import { StepperPanel } from 'primereact/stepperpanel'
import PrimaryButton from '@component/form/buttons/PrimaryButton'
import PrimaryOutlinedButton from '@component/form/buttons/PrimaryOutlinedButton'
import { ArrowDownIcon, ArrowUpIcon } from '@heroicons/react/24/outline'
import type { Attribute } from '../../../core/stores/ProjectStore'
import TrustDeck, { TrustDeckHttpError } from '../../../core/services/TrustDeck'
import useToastStore from '../../../core/stores/ToastStore'
import { canCurrentUserUseEntityTypeAction } from '../../../core/services/PermissionCache'

type Props = {
  entityName: string
  variant?: 'registration' | 'search'
}

export default function DynamicForm({
  entityName,
  variant = 'registration'
}: Props) {
  const { t, i18n } = useTranslation()
  const navigate = useNavigate()
  const showToast = useToastStore((state) => state.show)
  const entityAttributes = useProjectStore((state) => state.entityAttributes)
  const selectedProject = useProjectStore((state) => state.selectedProject)
  const entity = entityAttributes.find((e) => e.name === entityName)

  const [formValues, setFormValues] = useState<Record<string, any>>({})
  const [currentStep, setCurrentStep] = useState(0)
  const [registering, setRegistering] = useState(false)
  const stepperRef = useRef<any | null>(null)

  useEffect(() => {
    setCurrentStep(0)
  }, [entityName])

  if (!entity) {
    return <div>{t('entityBuilder:noEntityFound', { entityName })}</div>
  }

  const handleChange = (key: string, value: any) => {
    setFormValues((prev) => {
      const next = structuredClone(prev)
      setValue(next, key, value)
      return next
    })
  }

  const title = entityName.charAt(0).toUpperCase() + entityName.slice(1)
  const showRequired = variant === 'registration'
  const panelClassName = variant === 'search' ? 'w-full lg:w-full' : 'w-full'
  type RegistrationStep = {
    key: string
    name?: string
    labelEn?: string
    labelDe?: string
    attributes: Attribute[]
    pathPrefix?: string
  }

  // Each "layout: group" (or group=true for backward compatibility) is a step.
  const resolveGroupLabel = (
    group: Attribute,
    lang: 'en' | 'de'
  ): string | undefined => {
    const g = group as any
    const en = g.label_en
    const de = g.label_de
    return lang === 'de' ? (de ?? en ?? group.name) : (en ?? de ?? group.name)
  }

  const groupSteps: RegistrationStep[] = (
    entity.typeDefinition.attributes ?? []
  )
    .filter(
      (attr) =>
        Array.isArray(attr.attributes) &&
        (attr.layout === 'group' || attr.group === true)
    )
    .map((group, index) => ({
      key: `${group.key || group.name || entityName}-group-step-${index}`,
      name: group.name,
      labelEn: resolveGroupLabel(group, 'en'),
      labelDe: resolveGroupLabel(group, 'de'),
      attributes: group.attributes ?? [],
      // Keep payload keys stable and backend-friendly: only use semantic group names.
      // Do not use autogenerated UUID keys as payload prefixes.
      pathPrefix: group.name || ''
    }))

  const registrationSteps: RegistrationStep[] =
    groupSteps.length > 0
      ? groupSteps
      : [
          {
            key: `${entityName}-default-step`,
            labelEn: title,
            labelDe: title,
            attributes: entity.typeDefinition.attributes ?? [],
            pathPrefix: ''
          }
        ]

  const getStepTitle = (step: RegistrationStep, index: number) => {
    const lang = i18n.language || 'en'
    if (lang.startsWith('de')) {
      return step.labelDe ?? step.labelEn ?? step.name ?? `Schritt ${index + 1}`
    }
    return step.labelEn ?? step.labelDe ?? step.name ?? `Step ${index + 1}`
  }

  const handleNext = () => {
    setCurrentStep((prev) => prev + 1)
    stepperRef.current?.nextCallback()
  }

  const handlePrev = () => {
    setCurrentStep((prev) => prev - 1)
    stepperRef.current?.prevCallback()
  }

  const normalizeRepeatableGroups = (
    data: Record<string, any>,
    attributes: Attribute[]
  ): Record<string, any> => {
    const next = structuredClone(data)

    const normalizeNode = (container: any, attrs: Attribute[]) => {
      if (!container || typeof container !== 'object') return

      attrs.forEach((attr) => {
        if (!attr.name || !attr.attributes) return
        const current = container[attr.name]
        if (current == null) return

        if (attr.repeatable) {
          const arr = Array.isArray(current) ? current : [current]
          container[attr.name] = arr
          arr.forEach((item) => normalizeNode(item, attr.attributes ?? []))
          return
        }

        if (Array.isArray(current)) {
          current.forEach((item) => normalizeNode(item, attr.attributes ?? []))
        } else {
          normalizeNode(current, attr.attributes ?? [])
        }
      })
    }

    normalizeNode(next, attributes)
    return next
  }

  const handleRegister = async () => {
    if (
      !(await canCurrentUserUseEntityTypeAction(
        selectedProject?.abbreviation,
        entityName,
        'entity:create'
      ))
    ) {
      return
    }
    const normalizedData = normalizeRepeatableGroups(
      formValues,
      entity.typeDefinition.attributes ?? []
    )
    const payload = {
      projectName: selectedProject?.abbreviation,
      entityTypeName: entityName,
      data: normalizedData
    }
    try {
      setRegistering(true)
      const creationResult = await TrustDeck.instance().postEntityWithResult(
        entityName,
        payload
      )
      showToast({
        severity: 'success',
        summary: t('identity:buttons.register'),
        detail: creationResult.created
          ? t('identity:registerSuccess', 'Entity registered successfully')
          : t('identity:crud.existingEntityReturned'),
        life: 4000
      })
      navigate('/search')
    } catch (error) {
      if (error instanceof TrustDeckHttpError && error.status === 409) {
        let count = 0
        try {
          const candidates = JSON.parse(error.body)
          count = Array.isArray(candidates) ? candidates.length : 0
        } catch {
          count = 0
        }
        showToast({
          severity: 'warn',
          summary: t('identity:crud.linkageConflictTitle'),
          detail: t('identity:crud.linkageConflictText', { count }),
          life: 6000
        })
        return
      }
      console.error('Failed to register entity:', error)
      showToast({
        severity: 'error',
        summary: t('identity:buttons.register'),
        detail: error instanceof Error ? error.message : String(error),
        life: 5000
      })
    } finally {
      setRegistering(false)
    }
  }

  return (
    <Panel
      title={variant === 'registration' ? title : undefined}
      className={panelClassName}
      noBasePanel={variant === 'search'}
    >
      {variant === 'registration' ? (
        <>
          <Stepper
            key={`${entityName}-${registrationSteps.map((s) => s.key).join('|')}`}
            ref={stepperRef}
            orientation="vertical"
            activeStep={currentStep}
          >
            {registrationSteps.map((step, index) => {
              const stepPath = step.pathPrefix ?? step.name ?? ''
              return (
                <StepperPanel key={step.key} header={getStepTitle(step, index)}>
                  <p className="mb-4">{t('identity:requiredFieldsHint')}</p>

                  <div className="space-y-4">
                    {parseAttributes({
                      attributes: step.attributes,
                      values: formValues,
                      onChange: handleChange,
                      showRequired: true,
                      path: stepPath,
                      language: i18n.language
                    })}
                  </div>

                  <div className="flex py-4 space-x-4">
                    {index > 0 && (
                      <PrimaryOutlinedButton
                        label={
                          <span className="flex items-center gap-2">
                            {t('identity:buttons.back')}
                            <ArrowUpIcon className="h-5 w-5" />
                          </span>
                        }
                        onClick={handlePrev}
                      />
                    )}
                    {index < registrationSteps.length - 1 && (
                      <PrimaryButton
                        label={
                          <span className="flex items-center gap-2">
                            {t('identity:buttons.next')}
                            <ArrowDownIcon className="h-5 w-5" />
                          </span>
                        }
                        onClick={handleNext}
                      />
                    )}
                  </div>
                </StepperPanel>
              )
            })}
          </Stepper>
          <div className="flex justify-end my-4">
            <PrimaryButton
              label={t('identity:buttons.register')}
              disabled={currentStep !== registrationSteps.length - 1}
              loading={registering}
              onClick={handleRegister}
            />
          </div>
        </>
      ) : (
        <div className="space-y-4">
          {parseAttributes({
            attributes: entity.typeDefinition.attributes,
            values: formValues,
            onChange: handleChange,
            showRequired,
            language: i18n.language
          })}
        </div>
      )}
    </Panel>
  )
}
